defmodule VfpMcp.Development.IsolationPolicyTest do
  use ExUnit.Case, async: true

  alias VfpMcp.Development.IsolationPolicy

  # specled covers:
  # - vfp_mcp.boundary.development_isolation
  # - vfp_mcp.boundary.no_vfp_execution

  setup do
    workspace = Path.expand("../../..", __DIR__)
    temporary = Path.join(System.tmp_dir!(), "vfp_mcp_tests")

    policy =
      IsolationPolicy.new(workspace,
        disposable_roots: [temporary, ".vfp_mcp/test-work"],
        case_sensitive?: false
      )

    %{policy: policy, workspace: workspace, temporary: temporary}
  end

  test "permits generated bytes without a path", %{policy: policy} do
    assert :ok = IsolationPolicy.authorize(policy, :generated, nil)
    refute IsolationPolicy.allowed?(policy, :generated, "test/fixtures/example.scx")
  end

  test "permits only committed fixture paths under the fixture root", %{
    policy: policy,
    workspace: workspace
  } do
    assert :ok =
             IsolationPolicy.authorize(
               policy,
               :committed_fixture,
               "test/fixtures/vfp9/basic_form.scx"
             )

    assert :ok =
             IsolationPolicy.authorize(
               policy,
               :committed_fixture,
               Path.join(workspace, "TEST/FIXTURES/vfp6/basic_form.scx")
             )

    assert {:error, :source_outside_allowed_root} =
             IsolationPolicy.authorize(policy, :committed_fixture, "test/fixtures-other/a.scx")
  end

  test "permits disposable copies only under explicitly approved roots", %{
    policy: policy,
    temporary: temporary
  } do
    assert :ok =
             IsolationPolicy.authorize(
               policy,
               :disposable_copy,
               Path.join(temporary, "case-1/basic_form.scx")
             )

    assert :ok =
             IsolationPolicy.authorize(
               policy,
               :disposable_copy,
               ".vfp_mcp/test-work/case-2/basic_form.scx"
             )

    assert {:error, :source_outside_allowed_root} =
             IsolationPolicy.authorize(policy, :disposable_copy, "../outside/basic_form.scx")
  end

  test "rejects quarantined intake and unknown source kinds", %{policy: policy} do
    assert {:error, :raw_intake_forbidden} =
             IsolationPolicy.authorize(
               policy,
               :raw_intake,
               ".vfp_mcp/fixture-drop/vfp9/basic_form.scx"
             )

    assert {:error, :unknown_source_kind} =
             IsolationPolicy.authorize(policy, :original_application, "../LecoWin2/form.scx")
  end

  test "rejects missing paths and path traversal", %{policy: policy} do
    assert {:error, :path_required} =
             IsolationPolicy.authorize(policy, :committed_fixture, nil)

    assert {:error, :source_outside_allowed_root} =
             IsolationPolicy.authorize(
               policy,
               :committed_fixture,
               "test/fixtures/vfp9/../../../../sbt/source/form.scx"
             )

    assert {:error, :source_outside_allowed_root} =
             IsolationPolicy.authorize(
               policy,
               :committed_fixture,
               "C:/external/LecoWin2/form.scx"
             )
  end
end
