defmodule VfpMcp.Development.IsolationPolicy do
  @moduledoc """
  Pure authorization policy for repository development and automated tests.

  It is deliberately narrower than the deployed server boundary. The policy
  authorizes generated bytes, committed fixtures under `test/fixtures`, and
  disposable copies beneath explicitly named roots. Raw intake is never an
  executable test source.
  """

  # specled covers:
  # - vfp_mcp.boundary.development_isolation
  # - vfp_mcp.boundary.no_vfp_execution

  @enforce_keys [:workspace_root, :fixture_root, :disposable_roots, :case_sensitive?]
  defstruct [:workspace_root, :fixture_root, :disposable_roots, :case_sensitive?]

  @type source_kind :: :generated | :committed_fixture | :disposable_copy | :raw_intake

  @type reason ::
          :generated_source_has_path
          | :path_required
          | :raw_intake_forbidden
          | :source_outside_allowed_root
          | :unknown_source_kind

  @type t :: %__MODULE__{
          workspace_root: Path.t(),
          fixture_root: Path.t(),
          disposable_roots: [Path.t()],
          case_sensitive?: boolean()
        }

  @spec new(Path.t(), keyword()) :: t()
  def new(workspace_root, opts \\ []) when is_binary(workspace_root) and is_list(opts) do
    workspace_root = Path.expand(workspace_root)
    fixture_root = Path.expand(Keyword.get(opts, :fixture_root, "test/fixtures"), workspace_root)

    disposable_roots =
      opts
      |> Keyword.get(:disposable_roots, [".vfp_mcp/test-work"])
      |> Enum.map(&Path.expand(&1, workspace_root))
      |> Enum.uniq()

    %__MODULE__{
      workspace_root: workspace_root,
      fixture_root: fixture_root,
      disposable_roots: disposable_roots,
      case_sensitive?: Keyword.get(opts, :case_sensitive?, default_case_sensitive?())
    }
  end

  @spec authorize(t(), source_kind() | atom(), Path.t() | nil) ::
          :ok | {:error, reason()}
  def authorize(%__MODULE__{}, :generated, nil), do: :ok
  def authorize(%__MODULE__{}, :generated, _path), do: {:error, :generated_source_has_path}
  def authorize(%__MODULE__{}, :raw_intake, _path), do: {:error, :raw_intake_forbidden}

  def authorize(%__MODULE__{} = policy, :committed_fixture, path) when is_binary(path) do
    authorize_within(policy, path, [policy.fixture_root])
  end

  def authorize(%__MODULE__{} = policy, :disposable_copy, path) when is_binary(path) do
    authorize_within(policy, path, policy.disposable_roots)
  end

  def authorize(%__MODULE__{}, kind, nil)
      when kind in [:committed_fixture, :disposable_copy],
      do: {:error, :path_required}

  def authorize(%__MODULE__{}, _kind, _path), do: {:error, :unknown_source_kind}

  @spec allowed?(t(), source_kind() | atom(), Path.t() | nil) :: boolean()
  def allowed?(%__MODULE__{} = policy, kind, path) do
    authorize(policy, kind, path) == :ok
  end

  defp authorize_within(policy, path, roots) do
    candidate = Path.expand(path, policy.workspace_root)

    if Enum.any?(roots, &contains?(&1, candidate, policy.case_sensitive?)) do
      :ok
    else
      {:error, :source_outside_allowed_root}
    end
  end

  defp contains?(root, candidate, case_sensitive?) do
    root = comparable(root, case_sensitive?)
    candidate = comparable(candidate, case_sensitive?)
    candidate == root or String.starts_with?(candidate, root <> "/")
  end

  defp comparable(path, case_sensitive?) do
    normalized = path |> Path.expand() |> String.replace("\\", "/") |> String.trim_trailing("/")
    if case_sensitive?, do: normalized, else: String.downcase(normalized)
  end

  defp default_case_sensitive?, do: match?({:unix, _}, :os.type())
end
